title: Главная — Бухгалтерия
layout: rows
rows:
  - widgets:
      - БыстрыеДействия
  - widgets:
      - ОстатокКассы
      - ОстатокРасчётногоСчёта
      - Прибыль
  - widgets:
      - ДебиторскаяЗадолженность
      - КредиторскаяЗадолженность
